# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [15]:
# Create a 1-dimensional NumPy array using np.array()
a = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3], [3,4,5]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1], [2]], [[3], [4]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [16]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a.shape, a.dtype, a.size, type(a)

((3,), dtype('int64'), 3, numpy.ndarray)

In [17]:
# Attributes of 2-dimensional array
a2.shape, a2.dtype, a2.size, type(a2)

((2, 3), dtype('int64'), 6, numpy.ndarray)

In [18]:
# Attributes of 3-dimensional array
a3.shape, a3.dtype, a3.size, type(a3)

((2, 2, 1), dtype('int64'), 4, numpy.ndarray)

In [19]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
d1 = pd.DataFrame(a)
d2 = pd.DataFrame(a2)
d3 = pd.DataFrame()

In [20]:
# Create an array of shape (10, 2) with only ones
np.ones((10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
# Create an array of shape (7, 2, 3) of only zeros
np.zeros((7,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [22]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0, 100, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [23]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(10, size=(7,2))

array([[9, 7],
       [8, 5],
       [5, 2],
       [7, 7],
       [3, 6],
       [0, 7],
       [4, 1]])

In [26]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.random((3,5))

array([[0.89510745, 0.47908353, 0.5504816 , 0.05846057, 0.1596226 ],
       [0.88699592, 0.83413752, 0.73740435, 0.15116704, 0.5532148 ],
       [0.12677861, 0.23183325, 0.32969696, 0.53252509, 0.97656001]])

In [30]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(19, size=(4,6))

array([[ 6, 14, 10,  7,  6, 18],
       [10, 10,  3,  7,  2,  1],
       [11,  5,  1,  0, 11, 11],
       [16,  9, 15, 14, 14, 18]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [32]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arr = np.random.randint(1,10, size=(3,7))

# Find the unique numbers in the array you just created
arr, np.unique(arr)

(array([[1, 4, 2, 8, 4, 2, 6],
        [6, 4, 6, 2, 2, 4, 8],
        [7, 9, 8, 5, 2, 5, 8]]),
 array([1, 2, 4, 5, 6, 7, 8, 9]))

In [33]:
# Find the 0'th index of the latest array you created
arr[0]

array([1, 4, 2, 8, 4, 2, 6])

In [34]:
# Get the first 2 rows of latest array you created
arr[:2]

array([[1, 4, 2, 8, 4, 2, 6],
       [6, 4, 6, 2, 2, 4, 8]])

In [36]:
# Get the first 2 values of the first 2 rows of the latest array
arr[:2,:2]

array([[1, 4],
       [6, 4]])

In [51]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a1 = np.random.randint(10, size=(3,5))
a2 = np.ones((3,5))
a1

array([[4, 9, 6, 9, 8],
       [6, 8, 7, 1, 0],
       [6, 6, 7, 4, 2]])

In [52]:
# Add the two arrays together
a1 + a2

array([[ 5., 10.,  7., 10.,  9.],
       [ 7.,  9.,  8.,  2.,  1.],
       [ 7.,  7.,  8.,  5.,  3.]])

In [53]:
# Create another array of ones of shape (5, 3)
a3 = np.ones((5,3))

In [58]:
# Try add the array of ones and the other most recent array together
a4 = a2 + a3.T

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [59]:
# Create another array of ones of shape (3, 5)
a5 = np.ones((3,5))

In [60]:
# Subtract the new array of ones from the other most recent array
a4-a5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [61]:
# Multiply the ones array with the latest array
a4*a5

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [65]:
# Take the latest array to the power of 2 using '**'
a4 = a4**2

In [66]:
# Do the same thing with np.square()
np.square(a4)

array([[16., 16., 16., 16., 16.],
       [16., 16., 16., 16., 16.],
       [16., 16., 16., 16., 16.]])

In [70]:
# Find the mean of the latest array using np.mean()
arr = np.random.randint(10, size=(3,5))
arr.mean()

4.266666666666667

In [71]:
# Find the maximum of the latest array using np.max()
np.max(arr)

9

In [72]:
# Find the minimum of the latest array using np.min()
np.min(arr)

0

In [73]:
# Find the standard deviation of the latest array
np.std(arr)

2.4890872936792627

In [74]:
# Find the variance of the latest array
np.var(arr)

6.195555555555556

In [76]:
# Reshape the latest array to (3, 5, 1)
arr = arr.reshape(3,5,1)
arr

array([[[2],
        [6],
        [0],
        [3],
        [3]],

       [[4],
        [6],
        [6],
        [3],
        [6]],

       [[2],
        [5],
        [1],
        [9],
        [8]]])

In [82]:
# Transpose the latest array
arr = arr.T

In [83]:
arr

array([[[2, 4, 2],
        [6, 6, 5],
        [0, 6, 1],
        [3, 3, 9],
        [3, 6, 8]]])

What does the transpose do?

In [84]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr1 = np.random.randint(10, size=(3,3))
arr2 = np.random.randint(10, size=(3,2))

In [86]:
# Perform a dot product on the two newest arrays you created
arr3 = arr1.dot(arr2)
arr3

array([[ 53,  90],
       [106, 168],
       [ 48,  48]])

In [87]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
a1 = np.random.randint(10, size=(4,3))
a2 = np.random.randint(10, size=(4,3))

In [89]:
# Perform a dot product on the two newest arrays you created
a3 = np.dot(a1, a2.T)
a3

array([[72, 65, 42, 49],
       [18, 14, 16,  0],
       [45, 74, 38, 49],
       [27, 72, 26, 56]])

It doesn't work. How would you fix it?

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [102]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a1 = np.random.randint(10, size=(4,5))
a2 = np.random.randint(10, size=(4,5))

In [93]:
# Compare the two arrays with '>'
a1>a2

array([[False, False, False, False,  True],
       [ True, False, False, False, False],
       [ True,  True, False,  True,  True],
       [ True,  True, False, False,  True]])

What happens when you compare the arrays with `>`?

In [94]:
# Compare the two arrays with '>='
a1>=a2

array([[False, False,  True,  True,  True],
       [ True, False, False,  True, False],
       [ True,  True, False,  True,  True],
       [ True,  True, False, False,  True]])

In [95]:
# Find which elements of the first array are greater than 7
a1>7

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True, False, False, False],
       [False, False, False, False, False]])

In [96]:
# Which parts of each array are equal? (try using '==')
a1==a2

array([[False, False,  True,  True, False],
       [False, False, False,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [105]:
# Sort one of the arrays you just created in ascending order
a1.sort()
a1

array([[1, 1, 2, 8, 8],
       [1, 2, 3, 5, 8],
       [0, 0, 3, 3, 4],
       [0, 2, 6, 7, 7]])

In [106]:
# Sort the indexes of one of the arrays you just created
a1.argsort()

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [108]:
# Find the index with the maximum value in one of the arrays you've created
a1 = np.random.randint(10, size=(4,5))
a1, a1.argmax()

(array([[2, 7, 7, 1, 5],
        [6, 1, 9, 1, 9],
        [0, 7, 0, 8, 5],
        [6, 9, 6, 9, 2]]),
 7)

In [109]:
# Find the index with the minimum value in one of the arrays you've created
a1.argmin()

10

In [110]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
a1.argmax(axis=1)

array([1, 2, 3, 1])

In [111]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
a1.argmin(axis=0)

array([2, 1, 2, 0, 3])

In [117]:
# Create an array of normally distributed random numbers
s = np.random.randn(1,10)
s

array([[-0.98120034, -1.23823085, -0.82465133,  1.95128009, -0.04008514,
         0.52943551, -0.18389174, -0.09007863, -0.50588005,  0.05074396]])

In [124]:
# Create an array with 10 evenly spaced numbers between 1 and 100
a = np.linspace(1,100, 13)
a

array([  1.  ,   9.25,  17.5 ,  25.75,  34.  ,  42.25,  50.5 ,  58.75,
        67.  ,  75.25,  83.5 ,  91.75, 100.  ])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.