# Intro to Scikit-Learn

## End-to-end Scikit Learn workflow

In [7]:
import numpy as np

## 1. Get the data ready

In [1]:
import pandas as pd
heart_disease = pd.read_csv("heart-disease.csv")
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [2]:
# x features matrix
x = heart_disease.drop("target", axis=1)

# Y labels
y = heart_disease.target 

## 2. Choose the model

In [48]:
# choose model and hyperparameters
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)

# keep default hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

## Fit the model to the training data

In [49]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [50]:
x_train.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
239   35    1   0       126   282    0        0      156      1      0.0   
112   64    0   2       140   313    0        1      133      0      0.2   
251   43    1   0       132   247    1        0      143      1      0.1   
145   70    1   1       156   245    0        0      143      0      0.0   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
239      2   0     3  
112      2   0     3  
251      1   4     3  
145      2   0     2  
302      1   1     2

In [51]:
len(x_train)

242

In [52]:
len(x_test)

61

## Train the model

In [53]:
# find patterns in training data
clf.fit(x_train, y_train)

RandomForestClassifier()

## Make a prediction

In [54]:
y_preds = clf.predict(x_test)
y_preds

array([1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0])

In [55]:
clf.score(x_train, y_train)

1.0

In [56]:
clf.score(x_test, y_test)

0.7868852459016393

## Evaluate the model

In [57]:
# import classification tools
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [58]:
print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.73      0.76      0.75        25
           1       0.83      0.81      0.82        36

    accuracy                           0.79        61
   macro avg       0.78      0.78      0.78        61
weighted avg       0.79      0.79      0.79        61



In [59]:
confusion_matrix(y_test, y_preds)

array([[19,  6],
       [ 7, 29]])

In [60]:
accuracy_score(y_test, y_preds)

0.7868852459016393

## Improve the model

In [61]:
for i in range(10, 150):
    clf = RandomForestClassifier(n_estimators=i).fit(x_train, y_train)
    print(f"Model with {i} estimators achieved score of: {clf.score(x_test, y_test) * 100:.2f}%")

Model with 10 estimators achieved score of: 81.97%
Model with 11 estimators achieved score of: 78.69%
Model with 12 estimators achieved score of: 78.69%
Model with 13 estimators achieved score of: 80.33%
Model with 14 estimators achieved score of: 81.97%
Model with 15 estimators achieved score of: 86.89%
Model with 16 estimators achieved score of: 85.25%
Model with 17 estimators achieved score of: 77.05%
Model with 18 estimators achieved score of: 80.33%
Model with 19 estimators achieved score of: 78.69%
Model with 20 estimators achieved score of: 77.05%
Model with 21 estimators achieved score of: 78.69%
Model with 22 estimators achieved score of: 78.69%
Model with 23 estimators achieved score of: 83.61%
Model with 24 estimators achieved score of: 81.97%
Model with 25 estimators achieved score of: 78.69%
Model with 26 estimators achieved score of: 81.97%
Model with 27 estimators achieved score of: 81.97%
Model with 28 estimators achieved score of: 80.33%
Model with 29 estimators achiev

## Save the model 

In [62]:
import pickle

pickle.dump(clf, open("random_forest_model_1.pkl", "wb"))

## Import the model

In [63]:
loaded_model = pickle.load(open("random_forest_model_1.pkl", "rb"))
loaded_model.score(x_test, y_test)

0.819672131147541

# Getting data ready


## Three main things to do

1. Split data into features and labels (x, y)
2. Filling (called imputing) or disregarding missing values
3. Converting non-numberical values to numberical values (feauture encoding)

In [64]:
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [65]:
X = heart_disease.drop("target", axis=1)
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [66]:
y = heart_disease.target
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [67]:
# Split data into training and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [68]:
X_train.shape, x_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

### Make sure your data is numerical

In [69]:
# using another data set for presentation
# Try to predict a price of car

In [70]:
car_sales = pd.read_csv("data/car-sales-extended.csv")
car_sales.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [71]:
len(car_sales)

1000

In [73]:
# split data
X = car_sales.drop("Price", axis=1)
y = car_sales["Price"]

#Split into train and test data
X_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [74]:
# Build ML model
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train, y_train)
model.score(x_test, y_test)
# throws an error because of non-numerical fields

ValueError: could not convert string to float: 'Toyota'

In [75]:
X.head()

Make Colour  Odometer (KM)  Doors
0   Honda  White          35431      4
1     BMW   Blue         192714      5
2   Honda  White          84714      4
3  Toyota  White         154365      4
4  Nissan   Blue         181577      3

In [76]:
# Turn categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", one_hot, categorical_features)], remainder="passthrough")  

transformed_X = transformer.fit_transform(X)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [77]:
pd.DataFrame(transformed_X)

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [98]:
np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(transformed_X, y, test_size=0.2)
model.fit(X_train, y_train)

RandomForestRegressor()

In [99]:
model.score(X_test, y_test)

0.3235867221569877

 ### test / practice encoding

In [ ]:
# another way of transforming data to numerical
dummies = pd.get_dummies(car_sales[["Make", "Colour", "Doors"]])
dummies

In [80]:
tX = car_sales.drop(columns=["Price", "Colour", "Doors"])
tX

Make  Odometer (KM)
0     Honda          35431
1       BMW         192714
2     Honda          84714
3    Toyota         154365
4    Nissan         181577
..      ...            ...
995  Toyota          35820
996  Nissan         155144
997  Nissan          66604
998   Honda         215883
999  Toyota         248360

[1000 rows x 2 columns]

In [95]:
makes = np.sort(tX["Make"].unique())
makes

array(['BMW', 'Honda', 'Nissan', 'Toyota'], dtype=object)

In [82]:

categorical_features = ["Make"]
transformer = ColumnTransformer([("one_hot", OneHotEncoder(), categorical_features)], remainder="passthrough")

transformed_tX = transformer.fit_transform(tX)
pd.DataFrame(transformed_tX)

0    1    2    3         4
0    0.0  1.0  0.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  192714.0
2    0.0  1.0  0.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  154365.0
4    0.0  0.0  1.0  0.0  181577.0
..   ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0   35820.0
996  0.0  0.0  1.0  0.0  155144.0
997  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  248360.0

[1000 rows x 5 columns]